### ISSUE TITLE
Fix vulnérabilités potentielles sur le back

### ISSUE THREAD

**Issue by jja-octo** [octo-webf/francaisaletranger#14]
npm audit: 3 vulnerabilities
npm audit fix: 3 vulnerabilities required manual review and could not be updated

**Comment by jja-octo** [comment]
C'est parce que pour l'instant le projet API est sur un loopback obsolète - v3 au lieu de v4.

**Comment by jja-octo** [comment]
Ca implique de passer à loopback 4 qui serait un chantier assez gros

**Comment by XjulI1** [comment]
La vulnérabilité concerne l'`explorer`, composant qui n'est pas actif en production (que sur les postes des développeurs)

**Comment by XjulI1** [comment]
Et oui il faudrait passer à loopback 4 pour régler cela mais chantier très gros.
