### ISSUE TITLE
Se souvenir que le mail a déjà été envoyé et ne plus proposer de le faire

### ISSUE THREAD

**Issue by jja-octo** [octo-webf/francaisaletranger#54]

**Comment by XjulI1** [comment]
Doit pouvoir se gérer avec le fait qu'un ID de helper est renseigné dans la base de données pour une demande d'aide.

**Comment by XjulI1** [comment]
<img width="1011" alt="Capture d’écran 2020-03-24 à 19 37 58" src="https://user-images.githubusercontent.com/13014960/77464123-ff482a00-6e06-11ea-8150-40508be5815d.png">

**Comment by jja-octo** [comment]
@XjulI1 à bien tester avec le UUID que je viens de pusher
(les liens existants entre helper et needhelp ont été supprimés par la migration)
